services:
  mineonlium:
    restart: always
    command:
      - --genesis-file=/opt/besu/genesis/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-host=0.0.0.0
      - --graphql-http-enabled
      - --graphql-http-host=0.0.0.0
      - --p2p-host=0.0.0.0
      - --host-allowlist=*
      - --p2p-port=60606
      - --Xrpc-ipc-enabled
      - --bootnodes=enode://186fc7e1dc26686eaef6c9a57f33cc211650bc22b5152072f32593eb39f93ee3eb2c50e5e8d99905cd3021ff595f4c5b43a9d249d596d776649ba01f6dea8584@34.132.68.218:60606
      - --miner-stratum-enabled
      - --miner-stratum-host=0.0.0.0
      - --miner-stratum-port=50001
      - --miner-enabled=true
      - --miner-coinbase=$ADDRESS
      - --metrics-push-enabled 
      - --metrics-push-port=9091 
      - --metrics-push-host=push-gateway
    image: hyperledger/besu:latest
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 60606:60606
      - 50001:50001
    volumes:
      - ./modata:/opt/besu/data
      - ./genesis:/opt/besu/genesis
 

  #TODO:: CONFIGURE
  grafana:
    image: grafana/grafana:7.2.1
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    # volumes:
    #   - grafana:/etc/grafana/provisioning
    # env_file:
    #   - .grafana/config.monitoring
    restart: unless-stopped

  push-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  # #TODO:: CONFIGURE
  prometheus:
    image: prom/prometheus:v2.21.0
    depends_on:
      - mineonlium
    # volumes:
      # - ./prometheus/:/etc/prometheus
    command:
      # - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: unless-stopped
    ports:
      - 9090:9090

  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://mineonlium:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
    depends_on:
      - mongodb
    ports:
      - 8081:8081
  
  mongodb:
    image: mongo:5.0.8
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
    depends_on:
      - api
    ports:
      - 3000:3000

  
  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://mineonlium:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb

      




