version: '3.8'
# Blockscout
services:
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - ./redis-data:/data

  db:
    image: postgres:14
    restart: always
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
      - smart-contract-verifier
      - redis_db
    image: tmjeff/moscout:latest
    restart: always
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    restart: always
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043
# mineonlium node
  mineonlium:
    restart: always
    command:
      - --genesis-file=/opt/besu/genesis/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-host=0.0.0.0
      - --graphql-http-enabled
      - --graphql-http-host=0.0.0.0
      - --p2p-host=0.0.0.0
      - --host-allowlist=*
      - --p2p-port=60606
      - --Xrpc-ipc-enabled
      - --bootnodes=enode://186fc7e1dc26686eaef6c9a57f33cc211650bc22b5152072f32593eb39f93ee3eb2c50e5e8d99905cd3021ff595f4c5b43a9d249d596d776649ba01f6dea8584@34.132.68.218:60606
      - --miner-stratum-enabled
      - --miner-stratum-host=0.0.0.0
      - --miner-stratum-port=50001
      - --miner-enabled=true
      - --miner-coinbase=$ADDRESS
      - --metrics-push-enabled 
      - --metrics-push-port=9091 
      - --metrics-push-host=push-gateway
    image: hyperledger/besu:latest
    ports:
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 60606:60606
      - 50001:50001
    volumes:
      - ./modata:/opt/besu/data
      - ./genesis:/opt/besu/genesis
 

# Grafana 
  #TODO:: CONFIGURE
  grafana:
    image: grafana/grafana:7.2.1
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    # volumes:
    #   - grafana:/etc/grafana/provisioning
    # env_file:
    #   - .grafana/config.monitoring
    restart: unless-stopped

  push-gateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  # #TODO:: CONFIGURE
  prometheus:
    image: prom/prometheus:v2.21.0
    depends_on:
      - mineonlium
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: unless-stopped
    ports:
      - 9090:9090