global:
  scrape_interval:     15s # Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'besu-client'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['push-gateway:9091'] # refer system ip address rather that localhost